import dotenv from 'dotenv'

dotenv.config({ path: '.env.local' })

console.log('🔄 Force User Refresh Instructions')
console.log('')
console.log('Para forzar la actualización del usuario y obtener la foto correcta:')
console.log('')
console.log('1. Abre las herramientas de desarrollador (F12)')
console.log('2. Ve a la pestaña "Console" o "Consola"')
console.log('3. Ejecuta este código:')
console.log('')
console.log('// Limpiar localStorage')
console.log('localStorage.removeItem("farcaster-auth-user")')
console.log('')
console.log('// Recargar la página')
console.log('location.reload()')
console.log('')
console.log('O si quieres mantener la sesión pero forzar una actualización:')
console.log('')
console.log('// Obtener usuario actualizado desde la API')
console.log('fetch("/api/auth/farcaster?fid=497866")')
console.log('  .then(response => response.json())')
console.log('  .then(data => {')
console.log('    if (data.success) {')
console.log('      localStorage.setItem("farcaster-auth-user", JSON.stringify(data.data))')
console.log('      location.reload()')
console.log('    }')
console.log('  })')
console.log('')
console.log('Esto actualizará la información del usuario con la foto correcta de Farcaster.')
